From openjdk:8
EXPOSE 8769
copy ./target/target/CustomerConsumerClient-0.0.1-SNAPSHOT.jar target/CustomerConsumerClient-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","target/CustomerConsumerClient-0.0.1-SNAPSHOT.jar"]
